# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-27 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_auto_20170621_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mapa',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
